apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hqoas-spring-maven-pipeline
  namespace: tekton-tasks
spec:
  workspaces:
  - name: maven-repo
  - name: maven-settings

  params:
    - name: dockerfilePath
      type: string
      description: Path containing the Dockerfile for the final image
    - name: git-url
      type: string
      description: "Upstream Source Repository Url"
    - name: git-revision
      type: string
      description: "Upstream source code revision to pull"
    - name: image-name
      type: string
      description: "Target OCI image name"

  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: maven-repo

  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["clone"]
    params:
    - name: GOALS
      value: ["compile"]
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: package
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter: ["build"]
    params:
    - name: GOALS
      value: ["package"]
    workspaces:
    - name: source
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings

  - name: build-container-image
    runAfter: ["package"]
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: dockerconfig
      workspace: quay-credentials
    - name: source
      workspace: maven-repo
    params:
    - name: IMAGE
      value: $(params.image-name)
    - name: DOCKERFILE
      value: $(params.dockerfilePath)
