apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: generator-springboot-maven-pipeline-run-
  namespace: tekton-tasks
spec:
  pipelineRef:
    name: generator-springboot-maven-pipeline
  workspaces:
  - name: maven-settings
    emptyDir: {}
  - name: quay-credentials
  - name: maven-repo
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: git-revision
    value: generator-cicd
  - name: git-url
    value: https://github.com/janus-api-idp/yeoman-generators-spring-boot.git
  - name: image-name
    value: quay.io/bencheikhmohamedreda/generator-springboot:cluster
  - name: dockerfilePath
    value: .docker/Dockerfile